/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-21 08:44:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class find_005fid_005fsucc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1718955505860L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1718955502130L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n");
      out.write("\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:url\" content=\"사이트주소\">\r\n");
      out.write("<meta property=\"og:title\" content=\"냉장고를부탁해\">\r\n");
      out.write("<meta property=\"og:description\" content=\"사이트설명\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"사이트주소/images/common/kakao_logo_400x210.png\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"사이트설명\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"사이트관련키워드\" />\r\n");
      out.write("<meta name=\"classification\" content=\"사이트분류\" />\r\n");
      out.write("<meta name=\"author\" content=\"TeamChobao\" />\r\n");
      out.write("<meta name=\"title\" content=\"냉장고를부탁해\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"냉장고를부탁해\">\r\n");
      out.write("<meta name=\"subject\" content=\"사이트주제\" />\r\n");
      out.write("\r\n");
      out.write("<title>냉장고를부탁해</title>\r\n");
      out.write("\r\n");
      out.write("<!--Add Css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/swiper.min.css\" media=\"all\" />\r\n");
      out.write("<link href='https://unpkg.com/@fullcalendar/core@5.10.1/main.min.css' rel='stylesheet' />\r\n");
      out.write("<link href='https://unpkg.com/@fullcalendar/daygrid@5.10.1/main.min.css' rel='stylesheet' />\r\n");
      out.write("\r\n");
      out.write("<!--Basic Css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<!--Jquery Basic-->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.min.js\" charset=\"utf-8\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<!--Add Js-->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b9310abc97.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/swiper.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slider.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src='https://unpkg.com/@fullcalendar/core@5.10.1/main.min.js'></script>\r\n");
      out.write("<script src='https://unpkg.com/@fullcalendar/daygrid@5.10.1/main.min.js'></script>\r\n");
      out.write("<script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.14/index.global.min.js'></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/tooltipster/4.2.8/js/tooltipster.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--Basic Js-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		<header id=\"header\" class=\"px50\">\r\n");
      out.write("			<div class=\"hdr_inner\">\r\n");
      out.write("\r\n");
      out.write("				<h1 id=\"hdr_logo\">\r\n");
      out.write("					<a href=\"/\"><strong><span>냉장고를 </span>부탁해</strong></a>\r\n");
      out.write("				</h1>\r\n");
      out.write("\r\n");
      out.write("				<!-- Gnb -->\r\n");
      out.write("				<nav id=\"gnb\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"menu_dep1\">\r\n");
      out.write("								<a href=\"#\">my냉장고</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"menu_dep2\">\r\n");
      out.write("								<li>my냉장고</li>\r\n");
      out.write("								<li>품목 관리</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"menu_dep1\">\r\n");
      out.write("								<a href=\"#\">레시피</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"menu_dep2\">\r\n");
      out.write("								<li>레시피 검색</li>\r\n");
      out.write("								<li>추천 레시피</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a href=\"#\">정기구매</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"menu_dep1\">\r\n");
      out.write("								<a href=\"#\">고객센터</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"menu_dep2\">\r\n");
      out.write("								<li>FAQ</li>\r\n");
      out.write("								<li>1:1문의</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<!-- //Gnb -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"hdr_util\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li style=\"display: none;\"><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("						<li style=\"display: none;\"><a href=\"#\">로그아웃</a></li>\r\n");
      out.write("						<li><a href=\"#\">로그인</a></li>\r\n");
      out.write("						<li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!-- //Header -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Util Page -->\r\n");
      out.write("<main class=\"py120 util_page\">\r\n");
      out.write("\r\n");
      out.write("	<section id=\"util_box\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"big_tit\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				<strong>아이디 찾기 완료</strong>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"bdr_wrap\">\r\n");
      out.write("			<div class=\"find_result\">\r\n");
      out.write("\r\n");
      out.write("				<!-- 이름, 아이디 반환 -->\r\n");
      out.write("                <p class=\"font\">\r\n");
      out.write("                    ");
      out.print( request.getAttribute("userName") );
      out.write("님의 아이디는 &#34;<strong>");
      out.print( request.getAttribute("userId") );
      out.write("</strong>&#34; 입니다.\r\n");
      out.write("                </p>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn_wrap center my30\">\r\n");
      out.write("                <a href=\"#\" class=\"btn bdr w200\">비밀번호 찾기</a> <a href=\"login.jsp\"\r\n");
      out.write("                    class=\"btn grn w200\">로그인 하기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<!-- // Util Page -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer id=\"footer\" class=\"pdH\">\r\n");
      out.write("	<div class=\"ftr_inner\">\r\n");
      out.write("		<address>\r\n");
      out.write("			<span>대표자 : 홍길동</span> <span>사업자등록번호 : 000-00-0000</span> <span>주소\r\n");
      out.write("				: 광주광역시 동구 예술길</span> <span>대표전화 : 00-000-0000</span> <span>팩스 :\r\n");
      out.write("				00-000-0000</span>\r\n");
      out.write("		</address>\r\n");
      out.write("		<p class=\"copyright\">Copyright @ 2024 by Connected Inc. All Rights\r\n");
      out.write("			Reserved.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //Footer -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
