/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-21 03:29:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("    <meta http-equiv=\"cache-control\" content=\"no-cache\" />\r\n");
      out.write("    <meta http-equiv=\"expires\" content=\"0\" />\r\n");
      out.write("    <meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n");
      out.write("    <meta name=\"description\" content=\"냉장고를부탁해\" />\r\n");
      out.write("    <meta name=\"keywords\" content=\"냉장고를부탁해\" />\r\n");
      out.write("    <meta name=\"classification\" content=\"냉장고를부탁해\" />\r\n");
      out.write("    <meta name=\"author\" content=\"냉장고를부탁해\" />\r\n");
      out.write("    <meta name=\"title\" content=\"냉장고를부탁해\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-title\" content=\"냉장고를부탁해\">\r\n");
      out.write("    <meta name=\"subject\" content=\"냉장고를부탁해\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>냉장고를부탁해</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"images/common/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("    <link rel=\"icon\" href=\"images/common/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-ui.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Header -->\r\n");
      out.write("        <header id=\"header\" class=\"px50\">\r\n");
      out.write("            <div class=\"hdr_inner\">\r\n");
      out.write("\r\n");
      out.write("                <h1 id=\"hdr_logo\"><a href=\"/\"><strong><span>냉장고를 </span>부탁해</strong></a></h1>\r\n");
      out.write("\r\n");
      out.write("                <!-- Gnb -->\r\n");
      out.write("                <nav id=\"gnb\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"menu_dep1\"><a href=\"#\">my냉장고</a></div>\r\n");
      out.write("                            <ol class=\"menu_dep2\">\r\n");
      out.write("                                <li>my냉장고</li>\r\n");
      out.write("                                <li>품목 관리</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"menu_dep1\"><a href=\"#\">레시피</a></div>\r\n");
      out.write("                            <ol class=\"menu_dep2\">\r\n");
      out.write("                                <li>레시피 검색</li>\r\n");
      out.write("                                <li>추천 레시피</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\">정기구매</a></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"menu_dep1\"><a href=\"#\">고객센터</a></div>\r\n");
      out.write("                            <ol class=\"menu_dep2\">\r\n");
      out.write("                                <li>FAQ</li>\r\n");
      out.write("                                <li>1:1문의</li>\r\n");
      out.write("                            </ol>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- //Gnb -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"hdr_util\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li style=\"display: none;\"><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("                        <li style=\"display: none;\"><a href=\"#\">로그아웃</a></li>\r\n");
      out.write("                        <li><a href=\"#\">로그인</a></li>\r\n");
      out.write("                        <li><a href=\"MemberJoinCon\">회원가입</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- //Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Util Page -->\r\n");
      out.write("        <main class=\"py120 util_page\">\r\n");
      out.write("\r\n");
      out.write("            <section id=\"util_box\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"big_tit\">\r\n");
      out.write("                    <h3><strong class=\"font\">로그인</strong></h3>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 테이블 -->\r\n");
      out.write("                <form class=\"tb_wrap\" method=\"post\" action=\"MemberLoginCon\" name=\"\">\r\n");
      out.write("                    <div class=\"bdr_wrap row\" id=\"login\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <caption>로그인</caption>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"30%\">\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>아이디</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"text\" name=\"id\" maxlength=\"50\" placeholder=\"아이디를 입력해주세요\" value=\"");
      out.print( session.getAttribute("savedId") != null ? session.getAttribute("savedId") : "" );
      out.write("\" autofocus>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>비밀번호</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <input type=\"password\" name=\"pw\" maxlength=\"50\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("                        <div class=\"login_btns my20\">\r\n");
      out.write("                            <div class=\"lb\">\r\n");
      out.write("                                <div class=\"chk_box\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"save_id\" name=\"save_id\" class=\"login_chk\">\r\n");
      out.write("                                    <label for=\"save_id\">아이디 저장</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"chk_box\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"save_login\" name=\"save_login\" class=\"login_chk\">\r\n");
      out.write("                                    <label for=\"save_login\">자동로그인</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"rb\">\r\n");
      out.write("                                <span><a href=\"#\">아이디 찾기</a></span>\r\n");
      out.write("                                <span><a href=\"#\">비밀번호 찾기</a></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"btn_wrap my30\">\r\n");
      out.write("                            <a href=\"#\"><button type=\"submit\" class=\"btn_grn\">로그인</button></a>\r\n");
      out.write("                            <a href=\"#\"><button type=\"button\" class=\"btn_bg\">회원가입</button></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("        </main>\r\n");
      out.write("        <!-- // Util Page -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
