/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-24 05:28:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1718948872000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1719198014000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>냉장고를부탁해</title>\r\n");
      out.write("\r\n");
      out.write("<!--Add Js-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"http://code.jquery.com/jquery-latest.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b9310abc97.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src='https://unpkg.com/@fullcalendar/core@5.10.1/main.min.js'></script>\r\n");
      out.write("<script src='https://unpkg.com/@fullcalendar/daygrid@5.10.1/main.min.js'></script>\r\n");
      out.write("<script\r\n");
      out.write("	src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.14/index.global.min.js'></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/tooltipster/4.2.8/js/tooltipster.bundle.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/swiper.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/slider.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Basic Js-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Favicon-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/common/favicon.png\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/common/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Add Css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/swiper.min.css\" media=\"all\" />\r\n");
      out.write("<link href='https://unpkg.com/@fullcalendar/core@5.10.1/main.min.css'\r\n");
      out.write("	rel='stylesheet' />\r\n");
      out.write("<link href='https://unpkg.com/@fullcalendar/daygrid@5.10.1/main.min.css'\r\n");
      out.write("	rel='stylesheet' />\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"resources/styles.css\" type=\"text/css\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--Basic Css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		<header id=\"header\" class=\"px50\">\r\n");
      out.write("			<div class=\"hdr_inner\">\r\n");
      out.write("\r\n");
      out.write("				<h1 id=\"hdr_logo\">\r\n");
      out.write("					<a href=\"index.jsp\"><strong><span>냉장고를 </span>부탁해</strong></a>\r\n");
      out.write("				</h1>\r\n");
      out.write("\r\n");
      out.write("				<!-- Gnb -->\r\n");
      out.write("				<nav id=\"gnb\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"my_fridge.jsp\">my냉장고</a></li>\r\n");
      out.write("						<li><a href=\"calendar.jsp\">캘린더</a></li>\r\n");
      out.write("						<li><a href=\"recipe.jsp\">레시피</a></li>\r\n");
      out.write("						<li><a href=\"cs_center.jsp\">고객센터</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<!-- //Gnb -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"hdr_util\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"mem_info.jsp\">회원정보관리</a></li>\r\n");
      out.write("						<li><a href=\"MemberLogoutCon\">로그아웃</a></li>\r\n");
      out.write("						<li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("						<li><a href=\"join.html\">회원가입</a></li>\r\n");
      out.write("						\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!-- //Header -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Util Page -->\r\n");
      out.write("<main class=\"py120 util_page\">\r\n");
      out.write("\r\n");
      out.write("	<section id=\"util_box\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"big_tit\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				<strong class=\"font\">로그인</strong>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Form_Login -->\r\n");
      out.write("		<form class=\"tb_wrap\" method=\"post\" action=\"MemberLoginCon\"\r\n");
      out.write("			name=\"loginForm\">\r\n");
      out.write("			<div class=\"bdr_wrap row\" id=\"login\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<caption>로그인</caption>\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col width=\"30%\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>아이디</th>\r\n");
      out.write("							<td><input type=\"text\" name=\"id\" maxlength=\"50\"\r\n");
      out.write("								placeholder=\"아이디를 입력해주세요\"\r\n");
      out.write("								value=\"");
      out.print(session.getAttribute("savedId") != null ? session.getAttribute("savedId") : "");
      out.write("\"\r\n");
      out.write("								autofocus></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>비밀번호</th>\r\n");
      out.write("							<td><input type=\"password\" name=\"pw\" maxlength=\"50\"\r\n");
      out.write("								placeholder=\"비밀번호를 입력해주세요\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				<div class=\"login_btns my20\">\r\n");
      out.write("					<div class=\"lb\">\r\n");
      out.write("						<div class=\"chk_box\">\r\n");
      out.write("							<input type=\"checkbox\" id=\"save_id\" name=\"save_id\"\r\n");
      out.write("								class=\"login_chk\"> <label for=\"save_id\">아이디 저장</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"chk_box\">\r\n");
      out.write("							<input type=\"checkbox\" id=\"save_login\" name=\"save_login\"\r\n");
      out.write("								class=\"login_chk\"> <label for=\"save_login\">자동로그인</label>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"rb\">\r\n");
      out.write("						<span><a href=\"find_id.jsp\">아이디 찾기</a></span> <span><a href=\"find_pw.jsp\">비밀번호\r\n");
      out.write("								찾기</a></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn_wrap my30\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn grn\">로그인</button>\r\n");
      out.write("					<div class=\"line\">\r\n");
      out.write("						<a href=\"join.jsp\" class=\"btn bg\">회원가입</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<!-- //Form_Login -->\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<!-- // Util Page -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer id=\"footer\" class=\"pdH\">\r\n");
      out.write("	<div class=\"ftr_inner\">\r\n");
      out.write("		<address>\r\n");
      out.write("			<span>대표자 : 홍길동</span> <span>사업자등록번호 : 000-00-0000</span> <span>주소\r\n");
      out.write("				: 광주광역시 동구 예술길</span> <span>대표전화 : 00-000-0000</span> <span>팩스 :\r\n");
      out.write("				00-000-0000</span>\r\n");
      out.write("		</address>\r\n");
      out.write("		<p class=\"copyright\">Copyright @ 2024 by Connected Inc. All Rights\r\n");
      out.write("			Reserved.</p>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //Footer -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
