/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-21 04:08:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.smhrd.ingredient.model.IngredientDTO;
import java.util.List;

public final class my_005ffridge_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/smhrd/Desktop/핵심프로젝트/Take_care_of_the_fridge/revive/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/retry/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1718937872294L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.smhrd.ingredient.model.IngredientDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta http-equiv=\"imagetoolbar\" content=\"no\" />\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\" />\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\" />\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n");
      out.write("\r\n");
      out.write("<meta property=\"og:type\" content=\"website\">\r\n");
      out.write("<meta property=\"og:url\" content=\"사이트주소\">\r\n");
      out.write("<meta property=\"og:title\" content=\"냉장고를부탁해\">\r\n");
      out.write("<meta property=\"og:description\" content=\"사이트설명\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"사이트주소/images/common/kakao_logo_400x210.png\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"format-detection\" content=\"telephone=no\" />\r\n");
      out.write("<meta name=\"description\" content=\"사이트설명\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"사이트관련키워드\" />\r\n");
      out.write("<meta name=\"classification\" content=\"사이트분류\" />\r\n");
      out.write("<meta name=\"author\" content=\"TeamChobao\" />\r\n");
      out.write("<meta name=\"title\" content=\"냉장고를부탁해\">\r\n");
      out.write("<meta name=\"apple-mobile-web-app-title\" content=\"냉장고를부탁해\">\r\n");
      out.write("<meta name=\"subject\" content=\"사이트주제\" />\r\n");
      out.write("\r\n");
      out.write("<title>냉장고를부탁해</title>\r\n");
      out.write("\r\n");
      out.write("<!--Favicon-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"images/common/favicon.png\"\r\n");
      out.write("	type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"icon\" href=\"images/common/favicon.png\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<!--Add Css-->\r\n");
      out.write("\r\n");
      out.write("<!--Basic Css-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<!--Jquery Basic-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"http://code.jquery.com/jquery-latest.min.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--Add Js-->\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/b9310abc97.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--Basic Js-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/common.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-ui.min.js\" charset=\"utf-8\"></script> -->\r\n");
      out.write("<script>\r\n");
      out.write("	\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		<header id=\"header\" class=\"px50\">\r\n");
      out.write("			<div class=\"hdr_inner\">\r\n");
      out.write("\r\n");
      out.write("				<h1 id=\"hdr_logo\">\r\n");
      out.write("					<a href=\"/\"><strong><span>냉장고를 </span>부탁해</strong></a>\r\n");
      out.write("				</h1>\r\n");
      out.write("\r\n");
      out.write("				<!-- Gnb -->\r\n");
      out.write("				<nav id=\"gnb\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"menu_dep1\">\r\n");
      out.write("								<a href=\"#\">my냉장고</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"menu_dep2\">\r\n");
      out.write("								<li>my냉장고</li>\r\n");
      out.write("								<li>품목 관리</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"menu_dep1\">\r\n");
      out.write("								<a href=\"#\">레시피</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"menu_dep2\">\r\n");
      out.write("								<li>레시피 검색</li>\r\n");
      out.write("								<li>추천 레시피</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a href=\"#\">정기구매</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<div class=\"menu_dep1\">\r\n");
      out.write("								<a href=\"#\">고객센터</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ol class=\"menu_dep2\">\r\n");
      out.write("								<li>FAQ</li>\r\n");
      out.write("								<li>1:1문의</li>\r\n");
      out.write("							</ol>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<!-- //Gnb -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"hdr_util\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li style=\"display: none;\"><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("						<li style=\"display: none;\"><a href=\"#\">로그아웃</a></li>\r\n");
      out.write("						<li><a href=\"#\">로그인</a></li>\r\n");
      out.write("						<li><a href=\"#\">회원가입</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!-- //Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- container -->\r\n");
      out.write("		<main id=\"sub\">\r\n");
      out.write("			<section id=\"container\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Sub Visual -->\r\n");
      out.write("				<section id=\"sub_vis\" class=\"sv01\">\r\n");
      out.write("					<div id=\"sub_tit\" class=\"w1280\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<strong class=\"font\">my냉장고</strong>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<p>\r\n");
      out.write("							현재 냉장고에 보유중인 품목을 확인하고<br>간편하게 유통기한을 관리해보세요!\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("				<!-- Sub Content -->\r\n");
      out.write("				<section id=\"content\" class=\"my120\">\r\n");
      out.write("\r\n");
      out.write("					<!-- my냉장고품목 -->\r\n");
      out.write("					<section class=\"sub_cont w1280\">\r\n");
      out.write("						<div class=\"big_tit\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								<strong>my냉장고</strong>\r\n");
      out.write("							</h3>\r\n");
      out.write("							<p>이미지를 클릭하여 해당 칸에 보관된 식재료를 확인할 수 있습니다.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"s01_fridge\">\r\n");
      out.write("							<img src=\"images/sub/fridge.png\" alt=\"my냉장고\">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<!-- 품목리스트 -->\r\n");
      out.write("						<form class=\"tb_wrap\" action=\"\" name=\"\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mid_tit my20 loca\">\r\n");
      out.write("								<h4>\r\n");
      out.write("									<span>01</span><strong>냉장칸</strong>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"bdr_wrap\">\r\n");
      out.write("								<table class=\"fridge_list\">\r\n");
      out.write("									<caption>냉장칸 보유 품목</caption>\r\n");
      out.write("									<colgroup>\r\n");
      out.write("										<col width=\"50px\">\r\n");
      out.write("										<col>\r\n");
      out.write("										<col>\r\n");
      out.write("										<col width=\"15%\">\r\n");
      out.write("										<col width=\"15%\">\r\n");
      out.write("										<col width=\"20%\">\r\n");
      out.write("									</colgroup>\r\n");
      out.write("									<thead>\r\n");
      out.write("										<tr>\r\n");
      out.write("											<th>\r\n");
      out.write("												<div class=\"chk_box\">\r\n");
      out.write("													<input type=\"checkbox\" id=\"check_all\" class=\"chk\">\r\n");
      out.write("													<label for=\"check_all\"></label>\r\n");
      out.write("												</div>\r\n");
      out.write("											</th>\r\n");
      out.write("											<th>품목명</th>\r\n");
      out.write("											<th>수량</th>\r\n");
      out.write("											<th>구매날짜</th>\r\n");
      out.write("											<th>유통기한</th>\r\n");
      out.write("											<th>관리</th>\r\n");
      out.write("										</tr>\r\n");
      out.write("									</thead>\r\n");
      out.write("									<tbody>\r\n");
      out.write("										<!-- Java 코드로 ingredientList를 반복하며 데이터를 출력 -->\r\n");
      out.write("										");

										List<IngredientDTO> ingredientList = (List<IngredientDTO>) request.getAttribute("ingredientList");
										if (ingredientList != null) {
											for (IngredientDTO ingredient : ingredientList) {
										
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td>");
      out.print(ingredient.getIngre_name());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(ingredient.getIngre_stock());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(ingredient.getPurchased_at());
      out.write("</td>\r\n");
      out.write("											<td>");
      out.print(ingredient.getExpired_at());
      out.write("</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										");

										}
										} else {
										
      out.write("\r\n");
      out.write("										<tr>\r\n");
      out.write("											<td colspan=\"4\">보유중인 품목이 없습니다.</td>\r\n");
      out.write("										</tr>\r\n");
      out.write("										");

										}
										
      out.write("\r\n");
      out.write("									</tbody>\r\n");
      out.write("								</table>\r\n");
      out.write("\r\n");
      out.write("								<!-- 보관중인 품목이 없을 경우 보여지는 박스/ \r\n");
      out.write("                                        아래 전체,선택삭제 버튼도 마찬가지 -->\r\n");
      out.write("								<div class=\"info_box null_box\">\r\n");
      out.write("									<p class=\"ico_info\">보유중인 품목이 없습니다</p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"btn_wrap my30\">\r\n");
      out.write("								<div class=\"lb\"></div>\r\n");
      out.write("								<div class=\"rb\">\r\n");
      out.write("									<button class=\"btn_bg check_del\" type=\"button\">선택삭제</button>\r\n");
      out.write("									<button class=\"btn_grn btn_modal\" type=\"button\">품목추가</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("						<!-- 품목추가 팝업창 -->\r\n");
      out.write("						<div class=\"modal_box w1280 pa50\">\r\n");
      out.write("\r\n");
      out.write("							<div class=\"imgBlock btn_modal_close\">\r\n");
      out.write("								<a href=\"#;\"><img src=\"./images/sub/modal_close.png\"\r\n");
      out.write("									alt=\"팝업창 닫기\"></a>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"mid_tit\">\r\n");
      out.write("								<h4>\r\n");
      out.write("									<strong>품목 추가</strong>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<form action=\"IngredientAddCon\">\r\n");
      out.write("								<div class=\"bdr_wrap\">\r\n");
      out.write("									<table class=\"add_list\">\r\n");
      out.write("										<caption>품목 추가</caption>\r\n");
      out.write("										<colgroup>\r\n");
      out.write("											<col width=\"60px\">\r\n");
      out.write("											<col>\r\n");
      out.write("											<col width=\"18%\">\r\n");
      out.write("											<col width=\"10%\">\r\n");
      out.write("											<col>\r\n");
      out.write("											<col>\r\n");
      out.write("											<col>\r\n");
      out.write("											<col width=\"50px\">\r\n");
      out.write("										</colgroup>\r\n");
      out.write("										<thead>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th>No.</th>\r\n");
      out.write("												<th>품목명</th>\r\n");
      out.write("												<th>단위</th>\r\n");
      out.write("												<th>수량</th>\r\n");
      out.write("												<th>구매날짜</th>\r\n");
      out.write("												<th>유통기한</th>\r\n");
      out.write("												<th>위치</th>\r\n");
      out.write("												<th></th>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</thead>\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td>1</td>\r\n");
      out.write("												<td><input type=\"text\" name=\"name\" placeholder=\"품목명 입력\"></td>\r\n");
      out.write("												<td class=\"unit\">\r\n");
      out.write("													<div class=\"select_wrap\">\r\n");
      out.write("														<select name=\"unit\" class=\"select\" title=\"품목 단위\">\r\n");
      out.write("															<option selected>개</option>\r\n");
      out.write("															<option>ml</option>\r\n");
      out.write("														</select>\r\n");
      out.write("													</div> <input type=\"text\" class=\"unit_input\" name=\"unit_stock\"\r\n");
      out.write("													disabled>\r\n");
      out.write("												</td>\r\n");
      out.write("												<td class=\"qtt_num\"><input type=\"number\" name=\"stock\"\r\n");
      out.write("													value=\"1\"></td>\r\n");
      out.write("												<td class=\"date_picker\"><input type=\"date\"\r\n");
      out.write("													id=\"date_buy\" name=\"date_buy\" class=\"date_format\"\r\n");
      out.write("													onchange=\"formatDate()\"></td>\r\n");
      out.write("												<td class=\"date_picker\"><input type=\"date\"\r\n");
      out.write("													id=\"date_exp\" name=\"date_exp\" class=\"date_format\"\r\n");
      out.write("													onchange=\"formatDate()\"></td>\r\n");
      out.write("												<td>\r\n");
      out.write("													<div class=\"select_wrap loca\">\r\n");
      out.write("														<select name=\"location\" name=\"location\" class=\"select\"\r\n");
      out.write("															title=\"보관위치\">\r\n");
      out.write("															<option selected>냉장칸</option>\r\n");
      out.write("															<option>야채칸</option>\r\n");
      out.write("															<option>날개칸</option>\r\n");
      out.write("														</select>\r\n");
      out.write("													</div>\r\n");
      out.write("												</td>\r\n");
      out.write("												<td>\r\n");
      out.write("													<div class=\"row_del\">\r\n");
      out.write("														<a href=\"#;\"><img src=\"./images/sub/delete.png\"\r\n");
      out.write("															alt=\"행 삭제 버튼\"></a>\r\n");
      out.write("													</div>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"ico_info\">상품의 유통기한이 촬영된 사진을 업로드하시면 유통기한이 자동으로\r\n");
      out.write("									입력됩니다.</p>\r\n");
      out.write("								<div class=\"btn_wrap my30\">\r\n");
      out.write("\r\n");
      out.write("									<div class=\"lb\">\r\n");
      out.write("										<label for=\"file1\" class=\"btn_grn file_upload\">사진 업로드</label>\r\n");
      out.write("										<input type=\"file\" id=\"file1\" class=\"inpFile\"\r\n");
      out.write("											style=\"display: none;\">\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"rb\">\r\n");
      out.write("										<button class=\"btn_bg row_add\" type=\"button\">행 추가</button>\r\n");
      out.write("										<button class=\"btn_grn\" type=\"submit\">완료</button>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- // 품목추가 팝업창 -->\r\n");
      out.write("\r\n");
      out.write("					</section>\r\n");
      out.write("\r\n");
      out.write("					<!-- 팝업창 백그라운드 -->\r\n");
      out.write("					<div class=\"modal_back\"></div>\r\n");
      out.write("\r\n");
      out.write("				</section>\r\n");
      out.write("\r\n");
      out.write("			</section>\r\n");
      out.write("		</main>\r\n");
      out.write("		<!-- //container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		<footer id=\"footer\" class=\"pdH\">\r\n");
      out.write("			<div class=\"ftr_inner\">\r\n");
      out.write("				<address>\r\n");
      out.write("					<span>대표자 : 홍길동</span> <span>사업자등록번호 : 000-00-0000</span> <span>주소\r\n");
      out.write("						: 광주광역시 동구 예술길</span> <span>대표전화 : 00-000-0000</span> <span>팩스 :\r\n");
      out.write("						00-000-0000</span>\r\n");
      out.write("				</address>\r\n");
      out.write("				<p class=\"copyright\">Copyright @ 2024 by Connected Inc. All\r\n");
      out.write("					Rights Reserved.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("		<!-- //Footer -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
